name: Iris Train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }
        run: |
          # Your ML workflow goes here
          Makefile
          python src/train.py
 
        run: |
          # Post reports as comments in GitHub PRs
          cat reports/results.txt 
          # >> report.m
