name: Iris Train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      #- uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          make install
          python src/train.py
          python src/test.py
          echo '## Model Metrics' > report.md
          cat reports/train_metics.txt  >> report.md
          cat reports/test_metics.txt  >> report.md          
          cml-send-comment report.md
