name: Iris Train
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      #- uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          make install
          python src/train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat reports/train_metics.txt 
          # >> report.m
